### ISSUE TITLE
ImportError: cannot import name b

### ISSUE THREAD

**Issue by samarth-goel-guavus** [Grokzen/redis-py-cluster#294]
Redis 3.0.0 was released 1 hour back and it seems like redis-py-cluster is not compatible with it. Getting the following error:
```
venv/lib/python2.7/site-packages/rediscluster/__init__.py:7: in <module>
    from .client import StrictRedisCluster, RedisCluster
venv/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
venv/lib/python2.7/site-packages/rediscluster/client.py:10: in <module>
    from .connection import (
venv/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
venv/lib/python2.7/site-packages/rediscluster/connection.py:11: in <module>
    from .nodemanager import NodeManager
venv/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
venv/lib/python2.7/site-packages/rediscluster/nodemanager.py:12: in <module>
    from redis._compat import b, unicode, bytes, long, basestring
E   ImportError: cannot import name b
```

**Comment by Grokzen** [comment]
It looks like there is around ~220 commits between 2.10.6..3.0.0 so it will take some time to update the code to be compatible with both versions.

**Comment by Seanjimon** [comment]
https://github.com/andymccurdy/redis-py/commit/36a84fc9ac4e06a9b85ccc4e4eda426b387c7093

**Comment by samarth-goel-guavus** [comment]
So, should we restrict the version of `redis-py` at our end or will you restrict it for now?

**Comment by Grokzen** [comment]
I can add in the lock for it in the requirements spec and make a new minor release in the 1.3.x track.

**Comment by sicongliu-DD** [comment]
Same error here!!   **ImportError: cannot import name 'b'**

**Comment by pabloariasmora** [comment]
Having the same error, as quick-fix what I did was to add 
redis==2.10.6 as part of my project requirements file since [requirements.txt](https://github.com/Grokzen/redis-py-cluster/blob/unstable/requirements.txt) has >=2.10.6, you will get `Requirement already satisfied: redis>=2.10.6`

Commenting this just in case that somebody needs it.

**Comment by ostlerc** [comment]
ETA on fix?

**Comment by Grokzen** [comment]
Release 1.3.6 is now out. It has pinned version to 2.10.6 and no other code changes.

Will create a separate issue to update the code base to work with 3.0.0

**Comment by gcd0318** [comment]
so when will 1.3.x be supported, or supported by another branch?

**Comment by AvnerCohen** [comment]
This issue is preventing the upgrade of the redis client, pinned to 2.10.6 while latest is 3.2.1.
About two years in between these two versions.

Any ETA on this? Something the community can do to help push towards a fix maybe ?

**Comment by Grokzen** [comment]
@NoPretzel Check the latest 2.0.0 release before commenting on what is supported and not. Redis-py versions >= 3.0.0, < 3.1.0 is currently supported in the 2.0.x version track.
